sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: bL2YuYX2kZPSi6/fGWc/9QgC9vXU0fefJmhRoogo/LYuvd+hZVZi2/glhjABZ9z15pa0AKcfyksTNZZRy9sC63JOpI6frXNgMtyLwt7YyAmLuNvSXpKdgY5vf7YoFKkEi+9B8gkhDYY47BV+ecCtWt4KkJJPEGWzmwUjAPhyphULm6uQEHPL4688sOeh1EPb/ZOsvXam4X6ttTf6UI+oIlQki2x/1+JFRkffzETHJmsHm1m3LDISAYxV5HfqmpFb3wO4YrUL6qbemlrFW9o22fiXQb/cJCn4bIl8NX2cX3GPgapvIdc69oHWqeRhVHgkxdUduMFSI5cJLM9D1/yF3k5ZtrGhr2nkmel3JDxuGipbrNvhL2esFjOrIyySXxKJviyZgxLeWnPBP+R8RkNytr/3ZeS55RvAjpJX7Jn9fnKf0T27G/8aBfvHcnXoM54ojGHJ5VsgvrkvpeL/tg0IFUSGBVDtiYMIO70vKJqQQQfN8+tGJRcnO4QuJJnKAL7nWqyaRt+wltirF11zVmDhHzQSpPDCoASAsMaRTL4F4LskN645g/SF7T/6MKAZ3ksFSNEo99Ys6mw8RrIWMXaV+XLjqGfJc3c5J5XfM4tObhGOJhOCZJj1fZ2ZccT2N6N5HUpqVjNsrdYPrqKgB1u5jvMQ0zlBq5IXyxYQLPrXcBs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Winter-Sunshine_4279
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy